### ISSUE TITLE
Open footer links in new tab

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [galaxyproject/brc-analytics#183]
#### Approach
* Update BV-BRC and Pathogen Data Network footer links to open in a new tab.
* Confirm the `rel="noopener noreferrer"` tag is added to the link. (The Link component should automatically add this tag.)

**Comment by jpaten** [comment]
@MillenniumFalconMechanic  I think this is unfortunately a Findable issue!

It looks like rel="noopener referrer is being added, but the issue is that Findable sets target="_self" for all footer links ([code here](https://github.com/DataBiosphere/findable-ui/blob/46aef5560dee5bbf0c5db6d3ca47810dd763daac/src/components/Layout/components/Footer/footer.tsx#L39)), which causes it to never open in a new tab regardless of whether it's an internal or external link. Removing this makes it so that internal links open in the same tab and external links open in a new tab, so I'm not 100% sure what the purpose of it is.
